//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package spiglet.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(spiglet.visitor.Visitor v) throws Exception;
   public <R,A> R accept(spiglet.visitor.GJVisitor<R,A> v, A argu) throws Exception;
   public <R> R accept(spiglet.visitor.GJNoArguVisitor<R> v) throws Exception;
   public <A> void accept(spiglet.visitor.GJVoidVisitor<A> v, A argu) throws Exception;
}

